# gitlab runner
image: rocker/tidyverse

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

tests:
  stage: test
  tags:
    - docker
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - echo 'install.packages("knitrBootstrap")' | R
    - python3 --version
    - pip3 install .
    - pip3 install pytest-testdirectory
    - python3 setup.py test
